---
- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - haproxy
    - rsyslog
  become: true
  tags:
    - haproxy
    - rsyslog

- name: Configure service
  ansible.builtin.template:
    src: 'haproxy.cfg.j2'
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
    owner: haproxy
    group: haproxy
    validate: haproxy -f %s -c -q
  notify: Restart haproxy
  become: true
  tags:
    - haproxy
    - rsyslog

- name: Create rsyslog logging configuration
  ansible.builtin.copy:
    dest: /etc/rsyslog.d/haproxy.conf
    content: |
      # HAproxy Logging
      local2.*           /var/log/haproxy.log
    owner: root
    group: root
    mode: '0644'
  notify: Restart rsyslog
  become: true
  tags:
    - haproxy
    - rsyslog

- name: Configure rsyslog to accept network log events
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/rsyslog
    regexp: '^SYSLOGD_OPTIONS'
    line: 'SYSLOGD_OPTIONS="-r -m 0"'
    state: present
  notify: Restart rsyslog
  become: true
  tags:
    - haproxy
    - rsyslog

- name: Configure SELinux for HAProxy
  ansible.builtin.seport:
    ports: "{{ item }}"
    proto: tcp
    setype: haproxy_port_t
    state: present
  loop: "{{ haproxy_firewall_ports }}"
  when: ansible_selinux.status == 'enabled'
  become: true
  tags:
    - haproxy
    - rsyslog

- name: Start and enable service
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - haproxy
    - rsyslog
  become: true
  tags:
    - haproxy
    - rsyslog

- name: Flush all handlers
  ansible.builtin.meta: flush_handlers
  become: true
  tags:
    - haproxy
    - rsyslog
