---
- name: Create HAProxy SSL directory
  file:
    path: /etc/haproxy/ssl
    state: directory
    mode: 0755
    owner: haproxy
    group: haproxy
  tags: haproxy

- name: Generate a Self Signed OpenSSL certificate
  shell: openssl req -x509 -newkey rsa:4096 -keyout selfsigned.key -out selfsigned.crt -days 3650 -nodes -subj '/CN=selfsigned' && cat selfsigned.crt selfsigned.key > selfsigned.pem
  args:
    chdir: /etc/haproxy/ssl/
    creates: selfsigned.pem
  tags: haproxy