---
# tasks/main.yml
- name: "Erstelle VM {{ inventory_hostname }}"
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_automatic_hypervisor }}"
    api_user: "{{ proxmox_automatic_api_user }}"
    api_password: "{{ proxmox_automatic_api_password }}"
    node: "{{ proxmox_automatic_hypervisor.split('.')[0] }}"
    vmid: "{{ proxmox_automatic_vmid }}"
    name: "{{ inventory_hostname }}"
    memory: "{{ proxmox_automatic_memory | default(2048) }}"
    cores: "{{ proxmox_automatic_vcpu | default(2) }}"
    cpu: "{{ proxmox_automatic_cpu_type | default('x86-64-v3') }}"
    sockets: "{{ proxmox_automatic_sockets | default(1) }}"
    state: "{{ proxmox_automatic_state | default('present') }}"
    ide:
      ide2: "media=cdrom,{{ proxmox_automatic_storage | default(proxmox_automatic_pve_iso_storage) }}:iso/rocky9-ks.iso"
      ide3: "media=cdrom,{{ proxmox_automatic_storage | default(proxmox_automatic_pve_iso_storage) }}:iso/ks-{{ inventory_hostname }}.iso"
    bios: ovmf
    efidisk0:
      storage: "{{ proxmox_automatic_storage | default(proxmox_automatic_pve_vm_storage) }}"
      efitype: 4m
      format: raw
      pre_enrolled_keys: true
    tpmstate0:
      storage: "{{ proxmox_automatic_storage | default(proxmox_automatic_pve_vm_storage) }}"
    virtio:
      virtio0: "{{ proxmox_automatic_storage | default(proxmox_automatic_pve_vm_storage) }}:{{ proxmox_automatic_first_disk_size | regex_replace('[GM]', '') }},format={{ proxmox_vm_first_disk_format | default('qcow2') }}"
    net:
      net0: "virtio{% if proxmox_automatic_network[0].mac is defined %}={{ proxmox_automatic_network[0].mac }}{% else %},{% endif %},bridge={{ proxmox_automatic_network[0].bridge | default(proxmox_automatic_defaultbridge) }},tag={{ proxmox_automatic_network[0].vlanid }}{% if proxmox_automatic_network[0].mtu is defined %},{{ proxmox_automatic_network[0].mtu }}{% endif %}"
    kvm: "{{ proxmox_automatic_kvm | default(true) }}"
    ostype: "{{ proxmox_automatic_os_type | default('l26') }}"
    onboot: "{{ proxmox_automatic_onboot | default(true) }}"
    scsihw: "{{ proxmox_automatic_scsi_hw | default('virtio-scsi-single') }}"
    machine: "{{ proxmox_automatic_machine | default('q35') }}"
    hotplug: "{{ proxmox_automatic_hotplug | default('disk') }}"
    startup: "order={{ proxmox_automatic_boot_order | default(1) }},proxmox_automatic_up={{ boot_order_up_wait | default(3) }},proxmox_automatic_down={{ boot_order_down_wait | default(3) }}"
    agent: enabled=1
  delegate_to: localhost
  tags: create_vm

- name: "Add additional disks"
  community.general.proxmox_disk:
    api_host: "{{ proxmox_automatic_hypervisor }}"
    api_user: "{{ proxmox_automatic_api_user }}"
    api_password: "{{ proxmox_automatic_api_password }}"
    vmid: "{{ proxmox_automatic_vmid }}"
    disk: "{{ item.name }}"
    storage: "{{ item.storage | default(proxmox_automatic_pve_vm_storage) }}"
    size: "{{ item.size | regex_replace('[GM]', '') }}"
  loop: "{{ proxmox_automatic_disks | default([]) }}"
  loop_control:
    label: "{{ proxmox_automatic_hypervisor }} - {{ item.name }}"
  delegate_to: localhost
  tags: create_vm
  when: disks is defined and disks | length > 0

- name: "Add additional network adapters"
  community.general.proxmox_nic:
    api_host: "{{ proxmox_automatic_hypervisor }}"
    api_user: "{{ proxmox_automatic_api_user }}"
    api_password: "{{ proxmox_automatic_api_password }}"
    vmid: "{{ proxmox_automatic_vmid }}"
    interface: "{{ item.name }}"
    bridge: "{{ item.bridge | default('vmbr1') }}"
    tag: "{{ item.vlanid | default(0) }}"
    model: "{{ item.model | default('virtio') }}"
    mac: "{{ item.mac | default(omit) }}"
    mtu: "{{ item.mtu | default(omit) }}"
    rate: "{{ item.rate | default(omit) }}"
    state: "present"
  loop: "{{ proxmox_automatic_network | default([]) }}"
  loop_control:
    label: "{{ proxmox_automatic_hypervisor }} - {{ item.name }}"
  delegate_to: localhost
  tags: create_vm
  when: network is defined and network | length > 0

- name: "Start virtual machine"
  community.general.proxmox_kvm:
    api_host: "{{ proxmox_automatic_hypervisor }}"
    api_user: "{{ proxmox_automatic_api_user }}"
    api_password: "{{ proxmox_automatic_api_password }}"
    node: "{{ proxmox_automatic_hypervisor.split('.')[0] }}"
    vmid: "{{ proxmox_automatic_vmid }}"
    state: "started"
  delegate_to: localhost
  tags: create_vm
