---
# gitea version
# Use 'latest' to auto-update; upgrading past role version may lead to errors.
gitea_version: 'latest'
gitea_version_check: true
gitea_gpg_key: '7C9E68152594688862D62AF62D9AE806EC1592E2'
gitea_forgejo_gpg_key: 'EB114F5E6C0DC2BCDD183550A4B61A2DC5923710'
gitea_gpg_server: 'hkps://keys.openpgp.org'
gitea_gpg_keyserver_option: ''
gitea_backup_on_upgrade: false
gitea_backup_location: "{{ gitea_home }}/backups/"

# gitea in the linux world
gitea_user: 'git'
gitea_group: 'git'
# gitea_groups: []  # Optional a list of groups user gitea will be added to
gitea_home: '/var/lib/gitea'
gitea_user_home: '/home/{{ gitea_user }}'
gitea_executable_path: '/usr/local/bin/gitea'
gitea_configuration_path: '/etc/gitea'
gitea_shell: '/bin/false'
gitea_systemd_cap_net_bind_service: true

gitea_theme_default: "gitea-auto"
gitea_themes: "gitea-auto,gitea-light,gitea-dark"

# fail2ban
gitea_fail2ban_enabled: false
gitea_fail2ban_jail_maxretry: '10'
gitea_fail2ban_jail_findtime: '3600'
gitea_fail2ban_jail_bantime: '900'
gitea_fail2ban_jail_action: 'iptables-allports'

# gitea configuration
gitea_config:
  app_name: "Gitea"
  run_user: git
  work_path: "{{ gitea_home }}"
  run_mode: prod
  database:
    db_type: sqlite3
  server:
    domain: "{{ ansible_fqdn }}"
    http_port: 3000
    root_url: "http://{{ ansible_fqdn }}/"
    offline_mode: false
    landing_page: home
    protocol: http
    disable_http: false
    redirect_other_port: false
    port_to_redirect: 80
  service:
    register_email_confirm: false
    enable_notify_mail: false
    disable_registration: false
    require_signin_view: false
  mailer:
    enabled: false

# optional users on gitea instance
gitea_users: []
# example of entry
#  - name: johndoe
#    password: verysecret
#    email: "johndoe@example.com"
#    admin: false
#    must_change_password: true
#    state: present
