---
# Defaults
haproxy_default_mode: tcp
haproxy_default_log_format: ''
haproxy_timeout_connect: 6000
haproxy_timeout_client: 60000
haproxy_timeout_server: 60000
haproxy_defaultdhparam: 2048
haproxy_maxconn: 2048
# Security
haproxy_bind_ciphers: 'ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS:!CBC:!CCM'
haproxy_bind_options: 'no-sslv3 no-tlsv11 no-tlsv10'
haproxy_bind_ciphersuites: 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256'
# Web Stats
haproxy_stats_port: 8404
haproxy_stats_user: 'admin'
haproxy_stats_password: 'admin'
haproxy_stats_uri: '/stats'
# Prometheus Exporter
haproxy_prometheus_exporter_port: 9101

# Authentication
haproxy_userlists_list: []

# Frontends
haproxy_frontends_list: []

# Backends
haproxy_backends_list: []
