---
- name: Ensure packages are installed
  ansible.builtin.package:
    name: keepalived
    state: present
  become: true
  tags: keepalived

- name: Create configuration
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart keepalived
  become: true
  tags: keepalived

- name: Enable and start keepalived
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: true
  become: true
  tags: keepalived
