---
- name: Restart haproxy
  ansible.builtin.service:
    name: haproxy
    state: restarted
  become: true
  tags: haproxy

- name: Reload haproxy
  ansible.builtin.service:
    name: haproxy
    state: reloaded
  become: true
  tags: haproxy

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
  become: true
  tags: haproxy
