---
- name: Restart HAProxy
  service:
    name: haproxy
    state: restarted
  tags: haproxy

- name: Reload HAProxy
  service:
    name: haproxy
    state: reloaded
  tags: haproxy

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
  tags: haproxy